# Generated by Django 3.2.7 on 2022-05-10 10:00

import CustomUser.custom_models
import CustomUser.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_auto_20220510_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=CustomUser.custom_models.ImageField(blank=True, default='User profile images/default.png', help_text='Your image size should be between 0.5 - 2MB. <br>Please your a 2 x 2 image for between resolution.', upload_to='User profile images', validators=[CustomUser.validators.min_max_size]),
        ),
    ]
