# Generated by Django 3.2.7 on 2022-07-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_alter_clientsettings_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsettings',
            old_name='emailid',
            new_name='email_id',
        ),
    ]
