# Generated by Django 3.2.7 on 2022-07-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0008_rename_emailid_clientsettings_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsettings',
            name='name',
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CustomUser.customuser'),
            preserve_default=False,
        ),
    ]
