# Generated by Django 3.2.7 on 2022-07-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0009_auto_20220708_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsettings',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='clientsettings',
            name='profile',
        ),
    ]
