# Generated by Django 3.2.7 on 2022-07-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0010_auto_20220708_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsettings',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='clientsettings',
            name='last_updated',
        ),
    ]
