# Generated by Django 3.2.7 on 2022-07-14 11:19

import CustomUser.custom_models
import CustomUser.models
import CustomUser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0011_auto_20220708_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=CustomUser.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=CustomUser.custom_models.ImageField(blank=True, default='User profile images/default.png', help_text='Your image size should be between 0.5 - 2MB. <br>Please your a 2 x 2 image for between resolution.', upload_to=CustomUser.models.user_directory_path, validators=[CustomUser.validators.min_max_size]),
        ),
    ]
