# Generated by Django 3.2.7 on 2022-07-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0012_auto_20220714_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
