# Generated by Django 3.2.7 on 2022-05-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='User profile images'),
        ),
    ]
