# Generated by Django 3.2.7 on 2022-05-10 09:37

import CustomUser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_auto_20220503_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Joined date in our office.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='User profile images/default.png', help_text='Your image size should be between 0.5 - 2MB. <br>Please your a 2 x 2 image for between resolution.', upload_to='User profile images', validators=[CustomUser.validators.min_max_size]),
        ),
    ]
