# Generated by Django 3.2.7 on 2022-03-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=264, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ac', models.CharField(blank=True, max_length=25)),
                ('to_ac', models.CharField(blank=True, max_length=25)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('sender', models.CharField(blank=True, max_length=264, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=264, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
