# Generated by Django 3.2.7 on 2022-03-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0002_auto_20220329_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='payment_method',
        ),
    ]
