# Generated by Django 3.2.7 on 2022-03-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0003_rename_payment_type_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Check', 'Check'), ('Debit cards', 'Debit cards'), ('Credit cards', 'Credit cards'), ('Internet Banking', 'Internet Banking')], max_length=264, null=True),
        ),
    ]
