# Generated by Django 3.2.7 on 2022-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0005_auto_20220329_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
