# Generated by Django 3.2.7 on 2022-02-19 11:19

import BillingSystem.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('billno', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('goods_tax_id', models.CharField(blank=True, max_length=15)),
                ('pending_balance', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(default=BillingSystem.models.get_invoiceid, editable=False, max_length=20)),
                ('bill_note', models.TextField(blank=True)),
                ('bill_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bill_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('updated_time', models.TimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BillingSystem.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingSystem.invoice')),
            ],
        ),
    ]
