# Generated by Django 3.2.7 on 2022-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0007_auto_20220302_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
