# Generated by Django 3.2.7 on 2022-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0009_auto_20220315_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='industry_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
