# Generated by Django 3.2.7 on 2022-04-30 15:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0010_customer_industry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alter_mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
