# Generated by Django 3.2.7 on 2022-04-30 16:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0011_customer_alter_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='bill_paid_amount',
            new_name='cash_pay',
        ),
        migrations.AddField(
            model_name='invoice',
            name='upi_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alter_mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Alternate Mobile No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pending_balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
