# Generated by Django 3.2.7 on 2022-05-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0012_auto_20220430_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cash_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cash Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='upi_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Upi / Online Amount'),
        ),
    ]
