# Generated by Django 3.2.7 on 2022-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0013_auto_20220503_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
