# Generated by Django 3.2.7 on 2022-07-13 15:40

import BillingSystem.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0016_alter_customer_goods_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BillingSystem.customer', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=BillingSystem.models.get_invoiceid, editable=False, max_length=20, verbose_name='Invoice ID'),
        ),
    ]
