# Generated by Django 3.2.7 on 2022-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingSystem', '0004_auto_20220220_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pending_balance',
            field=models.IntegerField(default=0),
        ),
    ]
